from ROOT import TStyle

atlasStyle = TStyle("atlasStyle","atlasStyle")

atlasStyle.SetOptStat(0)
iCol=0
atlasStyle.SetFrameBorderMode(iCol)
atlasStyle.SetFrameFillColor(iCol)
atlasStyle.SetCanvasBorderMode(iCol)
atlasStyle.SetCanvasColor(iCol)
atlasStyle.SetPadBorderMode(iCol)
atlasStyle.SetPadColor(iCol)
atlasStyle.SetStatColor(iCol)
atlasStyle.SetPaperSize(20,26)
atlasStyle.SetPadTopMargin(0.05)
atlasStyle.SetPadRightMargin(0.05)
atlasStyle.SetPadBottomMargin(0.16)
atlasStyle.SetPadLeftMargin(0.16)
atlasStyle.SetTitleXOffset(1.4)
atlasStyle.SetTitleYOffset(1.4)
font=42
tSize=0.05
atlasStyle.SetTextFont(font)
atlasStyle.SetTextSize(tSize)
atlasStyle.SetLabelFont(font,"x")
atlasStyle.SetTitleFont(font,"x")
atlasStyle.SetLabelFont(font,"y")
atlasStyle.SetTitleFont(font,"y")
atlasStyle.SetLabelFont(font,"z")
atlasStyle.SetTitleFont(font,"z")
atlasStyle.SetLabelSize(tSize,"x")
atlasStyle.SetTitleSize(tSize,"x")
atlasStyle.SetLabelSize(tSize,"y")
atlasStyle.SetTitleSize(tSize,"y")
atlasStyle.SetLabelSize(tSize,"z")
atlasStyle.SetTitleSize(tSize,"z")
atlasStyle.SetMarkerStyle(20)
atlasStyle.SetMarkerSize(1.2)
atlasStyle.SetHistLineWidth(2)
atlasStyle.SetLineStyleString(2,"[12 12]")
atlasStyle.SetEndErrorSize(0.)
atlasStyle.SetOptTitle(0)
atlasStyle.SetOptFit(0)
atlasStyle.SetPadTickX(1)
atlasStyle.SetPadTickY(1)
atlasStyle.SetFrameFillColor(0)
atlasStyle.SetFrameBorderMode(0)
atlasStyle.SetCanvasBorderMode(0)
atlasStyle.SetCanvasColor(0)
atlasStyle.SetPadBorderMode(0)
atlasStyle.SetPadColor(0)
atlasStyle.SetTextFont(42)
atlasStyle.SetTextSize(0.04)
atlasStyle.SetTitleBorderSize(0)
atlasStyle.SetTitleFillColor(0)
