#ifndef CZ_FACEBOOK_ENABLE
#   define CZ_FACEBOOK_ENABLE 1
#endif
#ifndef I3D_OS_S3E
#   define I3D_OS_S3E 1
#endif
#ifndef I3D_PLATFORM_S3E
#   define I3D_PLATFORM_S3E 1
#endif
#ifndef IW_APP_NAME
#   define IW_APP_NAME "GameSceneGL"
#endif
#ifndef IW_APP_VERSION
#   define IW_APP_VERSION "1.0"
#endif
#ifndef IW_ASSERTION_CHANNEL_2D
#   define IW_ASSERTION_CHANNEL_2D 1
#endif
#ifndef IW_ASSERTION_CHANNEL_AMAZONINAPPPURCHASING
#   define IW_ASSERTION_CHANNEL_AMAZONINAPPPURCHASING 1
#endif
#ifndef IW_ASSERTION_CHANNEL_ANDROIDGOOGLEPLAYBILLING
#   define IW_ASSERTION_CHANNEL_ANDROIDGOOGLEPLAYBILLING 1
#endif
#ifndef IW_ASSERTION_CHANNEL_FACEBOOK
#   define IW_ASSERTION_CHANNEL_FACEBOOK 1
#endif
#ifndef IW_ASSERTION_CHANNEL_FIBRE
#   define IW_ASSERTION_CHANNEL_FIBRE 1
#endif
#ifndef IW_ASSERTION_CHANNEL_HTTP
#   define IW_ASSERTION_CHANNEL_HTTP 1
#endif
#ifndef IW_ASSERTION_CHANNEL_IOSAPPSTOREBILLING
#   define IW_ASSERTION_CHANNEL_IOSAPPSTOREBILLING 1
#endif
#ifndef IW_ASSERTION_CHANNEL_PVRTEXTOOL
#   define IW_ASSERTION_CHANNEL_PVRTEXTOOL 1
#endif
#ifndef IW_ASSERTION_CHANNEL_SAMSUNGINAPPPURCHASING
#   define IW_ASSERTION_CHANNEL_SAMSUNGINAPPPURCHASING 1
#endif
#ifndef IW_ASSERTION_CHANNEL_UTIL
#   define IW_ASSERTION_CHANNEL_UTIL 1
#endif
#ifndef IW_ASSERTION_CHANNEL_WEBVIEW
#   define IW_ASSERTION_CHANNEL_WEBVIEW 1
#endif
#ifndef IW_ASSERTION_CHANNEL_WINDOWSSTOREBILLING
#   define IW_ASSERTION_CHANNEL_WINDOWSSTOREBILLING 1
#endif
#ifndef IW_DEBUG
#   define IW_DEBUG 1
#endif
#ifndef IW_GXFONT_TTF
#   define IW_GXFONT_TTF 1
#endif
#ifndef IW_HTTP_SSL
#   define IW_HTTP_SSL 1
#endif
#ifndef IW_MKF_AMAZON_IN_APP_PURCHASING_ANDROID_SDK
#   define IW_MKF_AMAZON_IN_APP_PURCHASING_ANDROID_SDK 1
#endif
#ifndef IW_MKF_ANDROID_SUPPORT_V4
#   define IW_MKF_ANDROID_SUPPORT_V4 1
#endif
#ifndef IW_MKF_APPEASY
#   define IW_MKF_APPEASY 1
#endif
#ifndef IW_MKF_BOLTS_ANDROID
#   define IW_MKF_BOLTS_ANDROID 1
#endif
#ifndef IW_MKF_BOX2D
#   define IW_MKF_BOX2D 1
#endif
#ifndef IW_MKF_DERBH
#   define IW_MKF_DERBH 1
#endif
#ifndef IW_MKF_GAMESCENEGL_DEPLOYMENT
#   define IW_MKF_GAMESCENEGL_DEPLOYMENT 1
#endif
#ifndef IW_MKF_IW2D
#   define IW_MKF_IW2D 1
#endif
#ifndef IW_MKF_IWBILLING
#   define IW_MKF_IWBILLING 1
#endif
#ifndef IW_MKF_IWGEOM
#   define IW_MKF_IWGEOM 1
#endif
#ifndef IW_MKF_IWGL
#   define IW_MKF_IWGL 1
#endif
#ifndef IW_MKF_IWGX
#   define IW_MKF_IWGX 1
#endif
#ifndef IW_MKF_IWGXFONT
#   define IW_MKF_IWGXFONT 1
#endif
#ifndef IW_MKF_IWHTTP
#   define IW_MKF_IWHTTP 1
#endif
#ifndef IW_MKF_IWRESMANAGER
#   define IW_MKF_IWRESMANAGER 1
#endif
#ifndef IW_MKF_IWUTIL
#   define IW_MKF_IWUTIL 1
#endif
#ifndef IW_MKF_LIBJPEG
#   define IW_MKF_LIBJPEG 1
#endif
#ifndef IW_MKF_LIBPNG
#   define IW_MKF_LIBPNG 1
#endif
#ifndef IW_MKF_LSQLITE3
#   define IW_MKF_LSQLITE3 1
#endif
#ifndef IW_MKF_LUA_VEC
#   define IW_MKF_LUA_VEC 1
#endif
#ifndef IW_MKF_MARMALADE_FACEBOOK_ANDROID_SDK
#   define IW_MKF_MARMALADE_FACEBOOK_ANDROID_SDK 1
#endif
#ifndef IW_MKF_MARMALADE_FACEBOOK_IPHONE_SDK
#   define IW_MKF_MARMALADE_FACEBOOK_IPHONE_SDK 1
#endif
#ifndef IW_MKF_PVRTEXTOOL
#   define IW_MKF_PVRTEXTOOL 1
#endif
#ifndef IW_MKF_S3EAMAZONINAPPPURCHASING
#   define IW_MKF_S3EAMAZONINAPPPURCHASING 1
#endif
#ifndef IW_MKF_S3EANDROIDGOOGLEPLAYBILLING
#   define IW_MKF_S3EANDROIDGOOGLEPLAYBILLING 1
#endif
#ifndef IW_MKF_S3EFACEBOOK
#   define IW_MKF_S3EFACEBOOK 1
#endif
#ifndef IW_MKF_S3EIOSAPPSTOREBILLING
#   define IW_MKF_S3EIOSAPPSTOREBILLING 1
#endif
#ifndef IW_MKF_S3ESAMSUNGINAPPPURCHASING
#   define IW_MKF_S3ESAMSUNGINAPPPURCHASING 1
#endif
#ifndef IW_MKF_S3EWEBVIEW
#   define IW_MKF_S3EWEBVIEW 1
#endif
#ifndef IW_MKF_S3EWINDOWSSTOREBILLING
#   define IW_MKF_S3EWINDOWSSTOREBILLING 1
#endif
#ifndef IW_MKF_S3E_DEFAULT
#   define IW_MKF_S3E_DEFAULT 1
#endif
#ifndef IW_MKF_SOUNDENGINE
#   define IW_MKF_SOUNDENGINE 1
#endif
#ifndef IW_MKF_SQLITE
#   define IW_MKF_SQLITE 1
#endif
#ifndef IW_MKF_TINICONV
#   define IW_MKF_TINICONV 1
#endif
#ifndef IW_MKF_ZLIB
#   define IW_MKF_ZLIB 1
#endif
#ifndef IW_PLATFORM_S3E
#   define IW_PLATFORM_S3E 1
#endif
#ifndef IW_SDK
#   define IW_SDK 1
#endif
#ifndef IW_TRACE_CHANNEL_AMAZONINAPPPURCHASING
#   define IW_TRACE_CHANNEL_AMAZONINAPPPURCHASING 1
#endif
#ifndef IW_TRACE_CHANNEL_AMAZONINAPPPURCHASING_VERBOSE
#   define IW_TRACE_CHANNEL_AMAZONINAPPPURCHASING_VERBOSE 2
#endif
#ifndef IW_TRACE_CHANNEL_ANDROIDGOOGLEPLAYBILLING
#   define IW_TRACE_CHANNEL_ANDROIDGOOGLEPLAYBILLING 1
#endif
#ifndef IW_TRACE_CHANNEL_ANDROIDGOOGLEPLAYBILLING_VERBOSE
#   define IW_TRACE_CHANNEL_ANDROIDGOOGLEPLAYBILLING_VERBOSE 2
#endif
#ifndef IW_TRACE_CHANNEL_FACEBOOK
#   define IW_TRACE_CHANNEL_FACEBOOK 1
#endif
#ifndef IW_TRACE_CHANNEL_FACEBOOK_VERBOSE
#   define IW_TRACE_CHANNEL_FACEBOOK_VERBOSE 2
#endif
#ifndef IW_TRACE_CHANNEL_FIBRE
#   define IW_TRACE_CHANNEL_FIBRE 1
#endif
#ifndef IW_TRACE_CHANNEL_FIBRE_VERBOSE
#   define IW_TRACE_CHANNEL_FIBRE_VERBOSE 1
#endif
#ifndef IW_TRACE_CHANNEL_HTTP
#   define IW_TRACE_CHANNEL_HTTP 1
#endif
#ifndef IW_TRACE_CHANNEL_HTTP_VERBOSE
#   define IW_TRACE_CHANNEL_HTTP_VERBOSE 1
#endif
#ifndef IW_TRACE_CHANNEL_INAPPBILLING
#   define IW_TRACE_CHANNEL_INAPPBILLING 1
#endif
#ifndef IW_TRACE_CHANNEL_INAPPBILLING_VERBOSE
#   define IW_TRACE_CHANNEL_INAPPBILLING_VERBOSE 2
#endif
#ifndef IW_TRACE_CHANNEL_IOSAPPSTOREBILLING
#   define IW_TRACE_CHANNEL_IOSAPPSTOREBILLING 1
#endif
#ifndef IW_TRACE_CHANNEL_IOSAPPSTOREBILLING_VERBOSE
#   define IW_TRACE_CHANNEL_IOSAPPSTOREBILLING_VERBOSE 2
#endif
#ifndef IW_TRACE_CHANNEL_PVRTEXTOOL
#   define IW_TRACE_CHANNEL_PVRTEXTOOL 1
#endif
#ifndef IW_TRACE_CHANNEL_PVRTEXTOOL_VERBOSE
#   define IW_TRACE_CHANNEL_PVRTEXTOOL_VERBOSE 2
#endif
#ifndef IW_TRACE_CHANNEL_SAMSUNGINAPPPURCHASING
#   define IW_TRACE_CHANNEL_SAMSUNGINAPPPURCHASING 1
#endif
#ifndef IW_TRACE_CHANNEL_SAMSUNGINAPPPURCHASING_VERBOSE
#   define IW_TRACE_CHANNEL_SAMSUNGINAPPPURCHASING_VERBOSE 2
#endif
#ifndef IW_TRACE_CHANNEL_UTIL
#   define IW_TRACE_CHANNEL_UTIL 1
#endif
#ifndef IW_TRACE_CHANNEL_WEBVIEW
#   define IW_TRACE_CHANNEL_WEBVIEW 1
#endif
#ifndef IW_TRACE_CHANNEL_WEBVIEW_VERBOSE
#   define IW_TRACE_CHANNEL_WEBVIEW_VERBOSE 2
#endif
#ifndef IW_TRACE_CHANNEL_WINDOWSSTOREBILLING
#   define IW_TRACE_CHANNEL_WINDOWSSTOREBILLING 1
#endif
#ifndef IW_TRACE_CHANNEL_WINDOWSSTOREBILLING_VERBOSE
#   define IW_TRACE_CHANNEL_WINDOWSSTOREBILLING_VERBOSE 2
#endif
#ifndef IW_USE_ASSERTIONS
#   define IW_USE_ASSERTIONS 1
#endif
#ifndef IW_USE_CALLSTACK
#   define IW_USE_CALLSTACK 1
#endif
#ifndef IW_USE_TRACING
#   define IW_USE_TRACING 1
#endif
#ifndef S3E_INCLUDE_LEGACY
#   define S3E_INCLUDE_LEGACY 1
#endif
#ifndef SQLITE_OMIT_LOAD_EXTENSION
#   define SQLITE_OMIT_LOAD_EXTENSION 1
#endif
#ifndef TARGET_PLATFORM
#   define TARGET_PLATFORM MARMALADE
#endif
#ifndef __S3E__
#   define __S3E__ 1
#endif

/* including "extra_body" specified by the mkb plugin */

#if !defined I3D_ARCH_ARM && !defined I3D_ARCH_X86 && !defined I3D_ARCH_AARCH64 && !defined I3D_ARCH_NACLX86_64 && !defined I3D_ARCH_X86_64
    #if defined __ARMCC_VERSION || defined __arm__
        #define I3D_ARCH_ARM
    #elif defined __aarch64__
        #define I3D_ARCH_AARCH64
    #elif defined __x86_64__
        #define I3D_ARCH_X86_64
    #else
        #define I3D_ARCH_X86
        #define I3D_ARCH_I386
    #endif
#endif

#if defined I3D_ARCH_ARM || defined I3D_ARCH_X86 || defined I3D_ARCH_NACLX86_64
    #if defined I3D_ARCH_64_BIT
        #error "Preprocessor macro mismatch.  Current architecture is not 64 Bit"
    #endif
#else
    #ifdef I3D_ARCH_32_BIT
        #error "Preprocessor macro mismatch.  Current architecture is not 32 Bit"
    #endif
#endif

#if defined I3D_ARCH_X86 && !defined __i386__
    #define __i386__
#endif

#if defined I3D_ARCH_ARM && !defined __ARM__
    #define __ARM__
#endif
#if !defined I3D_ARCH_32_BIT && !defined I3D_ARCH_64_BIT
    #if defined I3D_ARCH_AARCH64 || defined I3D_ARCH_AMD64 || defined I3D_ARCH_X86_64
        #define I3D_ARCH_64_BIT
    #else
        #define I3D_ARCH_32_BIT
    #endif
#endif
